//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thanhhoa.gov.vn.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CNTTDHXDEntities : DbContext
    {
        public CNTTDHXDEntities()
            : base("name=CNTTDHXDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<gov_access_history> gov_access_history { get; set; }
        public DbSet<gov_access_module> gov_access_module { get; set; }
        public DbSet<gov_access_type> gov_access_type { get; set; }
        public DbSet<gov_advertise> gov_advertise { get; set; }
        public DbSet<gov_album_gallery> gov_album_gallery { get; set; }
        public DbSet<gov_answer> gov_answer { get; set; }
        public DbSet<gov_comments> gov_comments { get; set; }
        public DbSet<gov_course> gov_course { get; set; }
        public DbSet<gov_department> gov_department { get; set; }
        public DbSet<gov_district> gov_district { get; set; }
        public DbSet<gov_doc_draft> gov_doc_draft { get; set; }
        public DbSet<gov_doc_kind> gov_doc_kind { get; set; }
        public DbSet<gov_gallery> gov_gallery { get; set; }
        public DbSet<gov_group> gov_group { get; set; }
        public DbSet<gov_group_members> gov_group_members { get; set; }
        public DbSet<gov_group_permission> gov_group_permission { get; set; }
        public DbSet<gov_key_band> gov_key_band { get; set; }
        public DbSet<gov_level_district> gov_level_district { get; set; }
        public DbSet<gov_menu> gov_menu { get; set; }
        public DbSet<gov_message_system> gov_message_system { get; set; }
        public DbSet<gov_news> gov_news { get; set; }
        public DbSet<gov_notebook> gov_notebook { get; set; }
        public DbSet<gov_notify> gov_notify { get; set; }
        public DbSet<gov_person> gov_person { get; set; }
        public DbSet<gov_question> gov_question { get; set; }
        public DbSet<gov_question_category> gov_question_category { get; set; }
        public DbSet<gov_role> gov_role { get; set; }
        public DbSet<gov_slide_home> gov_slide_home { get; set; }
        public DbSet<gov_specialized> gov_specialized { get; set; }
        public DbSet<gov_statistic_access> gov_statistic_access { get; set; }
        public DbSet<gov_system_config> gov_system_config { get; set; }
        public DbSet<gov_testscore> gov_testscore { get; set; }
        public DbSet<gov_type_news> gov_type_news { get; set; }
        public DbSet<gov_user> gov_user { get; set; }
        public DbSet<gov_video> gov_video { get; set; }
        public DbSet<gov_work_schedule> gov_work_schedule { get; set; }
        public DbSet<gov_work_time> gov_work_time { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<gov_album> gov_album { get; set; }
    }
}
