//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thanhhoa.gov.vn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gov_doc_kind
    {
        public int kid { get; set; }
        public string kcode { get; set; }
        public string kname { get; set; }
        public string description { get; set; }
        public string update_username { get; set; }
        public System.DateTime update_datetime { get; set; }
    }
}
