//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thanhhoa.gov.vn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gov_user
    {
        public gov_user()
        {
            this.gov_group_members = new HashSet<gov_group_members>();
            this.gov_message_system = new HashSet<gov_message_system>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string family_name { get; set; }
        public string first_name { get; set; }
        public string birth_day { get; set; }
        public bool sex { get; set; }
        public string mobile { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public bool active_flg { get; set; }
        public bool hidden_flg { get; set; }
        public int role_id { get; set; }
        public int department_id { get; set; }
        public string avatar { get; set; }
        public string update_user_name { get; set; }
        public System.DateTime update_datetime { get; set; }
        public bool is_shared { get; set; }
        public string entry_username { get; set; }
        public System.DateTime entry_datetime { get; set; }
    
        public virtual gov_department gov_department { get; set; }
        public virtual ICollection<gov_group_members> gov_group_members { get; set; }
        public virtual ICollection<gov_message_system> gov_message_system { get; set; }
        public virtual gov_role gov_role { get; set; }
    }
}
