//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thanhhoa.gov.vn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gov_group
    {
        public gov_group()
        {
            this.gov_group_members = new HashSet<gov_group_members>();
            this.gov_group_permission = new HashSet<gov_group_permission>();
        }
    
        public int id { get; set; }
        public string group_name { get; set; }
        public bool hidden_flg { get; set; }
        public string update_username { get; set; }
        public System.DateTime update_datetime { get; set; }
        public string entry_username { get; set; }
        public System.DateTime entry_datetime { get; set; }
    
        public virtual ICollection<gov_group_members> gov_group_members { get; set; }
        public virtual ICollection<gov_group_permission> gov_group_permission { get; set; }
    }
}
