//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thanhhoa.gov.vn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gov_level_district
    {
        public gov_level_district()
        {
            this.gov_district = new HashSet<gov_district>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int order_number { get; set; }
        public string update_username { get; set; }
        public System.DateTime update_datetime { get; set; }
    
        public virtual ICollection<gov_district> gov_district { get; set; }
    }
}
