//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thanhhoa.gov.vn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gov_testscore
    {
        public int id { get; set; }
        public string test_name { get; set; }
        public string test_class { get; set; }
        public string attach_file_name { get; set; }
        public string entry_username { get; set; }
        public System.DateTime entry_datetime { get; set; }
        public string update_username { get; set; }
        public System.DateTime update_datetime { get; set; }
        public string namhoc { get; set; }
        public string kythi { get; set; }
        public string attach_file_path { get; set; }
        public string file_format { get; set; }
    }
}
