//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thanhhoa.gov.vn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gov_notebook
    {
        public int id { get; set; }
        public int specialized_id { get; set; }
        public int course_id { get; set; }
        public string lop { get; set; }
        public string title { get; set; }
        public string remember { get; set; }
        public string teacher { get; set; }
        public string dream { get; set; }
        public string note { get; set; }
        public bool active_flg { get; set; }
        public System.DateTime entry_datetime { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
    
        public virtual gov_course gov_course { get; set; }
        public virtual gov_specialized gov_specialized { get; set; }
    }
}
