//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thanhhoa.gov.vn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gov_system_config
    {
        public int id { get; set; }
        public string key_config { get; set; }
        public string lable_config { get; set; }
        public string value_config { get; set; }
        public string update_username { get; set; }
        public System.DateTime update_datetime { get; set; }
    }
}
