//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thanhhoa.gov.vn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gov_specialized
    {
        public gov_specialized()
        {
            this.gov_notebook = new HashSet<gov_notebook>();
            this.gov_person = new HashSet<gov_person>();
        }
    
        public int id { get; set; }
        public string specialized_name { get; set; }
        public System.DateTime update_datetime { get; set; }
        public string update_username { get; set; }
        public string entry_username { get; set; }
        public System.DateTime entry_datetime { get; set; }
    
        public virtual ICollection<gov_notebook> gov_notebook { get; set; }
        public virtual ICollection<gov_person> gov_person { get; set; }
    }
}
