//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thanhhoa.gov.vn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gov_comments
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string full_name { get; set; }
        public string email { get; set; }
        public Nullable<int> parent_id { get; set; }
        public int news_id { get; set; }
        public string comments_content { get; set; }
        public Nullable<int> total_like { get; set; }
        public string like_info { get; set; }
        public bool active_flg { get; set; }
        public System.DateTime entry_datetime { get; set; }
    }
}
