//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thanhhoa.gov.vn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gov_question_category
    {
        public gov_question_category()
        {
            this.gov_question = new HashSet<gov_question>();
        }
    
        public int id { get; set; }
        public string category_name { get; set; }
        public string description { get; set; }
        public int order_number { get; set; }
        public string update_username { get; set; }
        public System.DateTime update_datetime { get; set; }
    
        public virtual ICollection<gov_question> gov_question { get; set; }
    }
}
