//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thanhhoa.gov.vn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gov_answer
    {
        public int id { get; set; }
        public int question_id { get; set; }
        public bool hidden_flg { get; set; }
        public string answer_content { get; set; }
        public string answer_username { get; set; }
        public string update_username { get; set; }
        public System.DateTime answer_datetime { get; set; }
        public System.DateTime update_datetime { get; set; }
    
        public virtual gov_question gov_question { get; set; }
    }
}
