//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thanhhoa.gov.vn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gov_access_history
    {
        public int id { get; set; }
        public System.DateTime time_access { get; set; }
        public string client_info { get; set; }
        public string public_info { get; set; }
        public string username_access { get; set; }
        public int type_access { get; set; }
        public string description { get; set; }
    
        public virtual gov_access_type gov_access_type { get; set; }
    }
}
