//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thanhhoa.gov.vn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gov_access_type
    {
        public gov_access_type()
        {
            this.gov_access_history = new HashSet<gov_access_history>();
        }
    
        public int id { get; set; }
        public string type_name { get; set; }
        public int module_id { get; set; }
    
        public virtual ICollection<gov_access_history> gov_access_history { get; set; }
        public virtual gov_access_module gov_access_module { get; set; }
    }
}
