//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thanhhoa.gov.vn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gov_doc_draft
    {
        public int id { get; set; }
        public string doc_code { get; set; }
        public string doc_name { get; set; }
        public string doc_summany { get; set; }
        public string doc_content { get; set; }
        public bool doc_type { get; set; }
        public Nullable<double> score { get; set; }
        public System.DateTime date_start_promulgate { get; set; }
        public string user_sign { get; set; }
        public Nullable<bool> active_flg { get; set; }
        public string note { get; set; }
        public string attach_file_name { get; set; }
        public string attach_file_path { get; set; }
        public System.DateTime update_datetime { get; set; }
        public string update_username { get; set; }
        public string entry_username { get; set; }
        public System.DateTime entry_datetime { get; set; }
    }
}
