//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thanhhoa.gov.vn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gov_album
    {
        public gov_album()
        {
            this.gov_album_gallery = new HashSet<gov_album_gallery>();
        }
    
        public int id { get; set; }
        public string album_title { get; set; }
        public string description { get; set; }
        public string avatar { get; set; }
        public Nullable<int> total_view { get; set; }
        public Nullable<int> order_number { get; set; }
        public string update_username { get; set; }
        public System.DateTime update_datetime { get; set; }
        public string entry_username { get; set; }
        public System.DateTime entry_datetime { get; set; }
    
        public virtual ICollection<gov_album_gallery> gov_album_gallery { get; set; }
    }
}
