//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thanhhoa.gov.vn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gov_news
    {
        public int id { get; set; }
        public int menu_id { get; set; }
        public Nullable<int> type_id { get; set; }
        public string title { get; set; }
        public string avatar { get; set; }
        public string description { get; set; }
        public string new_content { get; set; }
        public string new_source { get; set; }
        public int total_view { get; set; }
        public bool is_tinlq { get; set; }
        public bool is_comment { get; set; }
        public bool is_shared { get; set; }
        public bool is_home { get; set; }
        public Nullable<double> score { get; set; }
        public bool active_flg { get; set; }
        public string entry_username { get; set; }
        public System.DateTime entry_datetime { get; set; }
        public string update_username { get; set; }
        public System.DateTime update_datetime { get; set; }
        public string meta_keyword { get; set; }
        public string meta_desciption { get; set; }
    
        public virtual gov_menu gov_menu { get; set; }
    }
}
