//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thanhhoa.gov.vn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gov_district
    {
        public int id { get; set; }
        public string name { get; set; }
        public int level { get; set; }
        public string decription { get; set; }
        public string link { get; set; }
        public int order_number { get; set; }
        public bool show_map { get; set; }
        public string coordinates { get; set; }
        public string update_username { get; set; }
        public System.DateTime update_datetime { get; set; }
    
        public virtual gov_level_district gov_level_district { get; set; }
    }
}
