//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thanhhoa.gov.vn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gov_question
    {
        public gov_question()
        {
            this.gov_answer = new HashSet<gov_answer>();
        }
    
        public int id { get; set; }
        public string full_name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string department { get; set; }
        public string title { get; set; }
        public bool hidden_flg { get; set; }
        public int category_id { get; set; }
        public string attach_file_name { get; set; }
        public string attach_file_path { get; set; }
        public string question_content { get; set; }
        public System.DateTime question_datetime { get; set; }
    
        public virtual ICollection<gov_answer> gov_answer { get; set; }
        public virtual gov_question_category gov_question_category { get; set; }
    }
}
