//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thanhhoa.gov.vn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gov_department
    {
        public gov_department()
        {
            this.gov_user = new HashSet<gov_user>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int order_number { get; set; }
        public string link { get; set; }
        public bool is_home { get; set; }
        public string update_username { get; set; }
        public System.DateTime update_datetime { get; set; }
        public string entry_username { get; set; }
        public System.DateTime entry_datetime { get; set; }
    
        public virtual ICollection<gov_user> gov_user { get; set; }
    }
}
