//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thanhhoa.gov.vn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gov_work_schedule
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public int time { get; set; }
        public string description { get; set; }
        public string location { get; set; }
        public string person_execute { get; set; }
        public string update_username { get; set; }
        public System.DateTime update_datetime { get; set; }
    
        public virtual gov_work_time gov_work_time { get; set; }
    }
}
