//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thanhhoa.gov.vn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gov_access_module
    {
        public gov_access_module()
        {
            this.gov_access_type = new HashSet<gov_access_type>();
        }
    
        public int id { get; set; }
        public string module_name { get; set; }
    
        public virtual ICollection<gov_access_type> gov_access_type { get; set; }
    }
}
