//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thanhhoa.gov.vn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gov_message_system
    {
        public int id { get; set; }
        public string username { get; set; }
        public string content_message { get; set; }
        public int type_message { get; set; }
        public System.DateTime entry_datetime { get; set; }
        public bool status { get; set; }
        public string link { get; set; }
    
        public virtual gov_user gov_user { get; set; }
    }
}
