//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thanhhoa.gov.vn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gov_menu
    {
        public gov_menu()
        {
            this.gov_news = new HashSet<gov_news>();
        }
    
        public int id { get; set; }
        public int id_parent { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public bool ishome { get; set; }
        public bool isleft { get; set; }
        public bool isrss { get; set; }
        public Nullable<int> order_number { get; set; }
        public string link { get; set; }
        public bool active_flg { get; set; }
        public string entry_username { get; set; }
        public System.DateTime entry_datetime { get; set; }
        public string update_username { get; set; }
        public System.DateTime update_datetime { get; set; }
        public string avatar { get; set; }
    
        public virtual ICollection<gov_news> gov_news { get; set; }
    }
}
