//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thanhhoa.gov.vn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gov_work_time
    {
        public gov_work_time()
        {
            this.gov_work_schedule = new HashSet<gov_work_schedule>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<gov_work_schedule> gov_work_schedule { get; set; }
    }
}
